services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ddmseoul_wp_demo_prod_db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    ports:
      - 80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ddmseoul_wp_demo-http.rule=Host(`ddmseoul_wp_demo.louislabs.com`)"
      - "traefik.http.routers.ddmseoul_wp_demo-http.entrypoints=web"
      - "traefik.http.routers.ddmseoul_wp_demo-http.middlewares=ddmseoul_wp_demo-https"
      - "traefik.http.middlewares.ddmseoul_wp_demo-https.redirectscheme.scheme=https"
      - "traefik.http.routers.ddmseoul_wp_demo.rule=Host(`ddmseoul_wp_demo.louislabs.com`)"
      - "traefik.http.routers.ddmseoul_wp_demo.entrypoints=websecure"
      - "traefik.http.routers.ddmseoul_wp_demo.tls.certresolver=myresolver"
      # - "traefik.http.services.ddmseoul_wp_demo.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: traefik-proxy-network

volumes:
  ddmseoul_wp_demo_prod_db_data:
